services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django123
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"  # <-- Changed host port to 3307
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
